//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellMonsterTable
    {
        public int Id { get; set; }
        public int SpellId { get; set; }
        public int MonsterId { get; set; }
    
        public virtual Spell Spell { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
