//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abilities
    {
        public int Id { get; set; }
        public short Strength { get; set; }
        public short Dexterity { get; set; }
        public short Constitution { get; set; }
        public short Intelligence { get; set; }
        public short Wisdom { get; set; }
        public short Charisma { get; set; }
        public short Proficiency_Bonus { get; set; }
    
        public virtual Monster Monster { get; set; }
    }
}
