//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DifficultyClass
    {
        public int Id { get; set; }
        public string DC_Type { get; set; }
        public short DC_Value { get; set; }
        public int LegendaryActionId { get; set; }
        public int ActionId { get; set; }
        public int LegendaryActionId1 { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual LegendaryAction LegendaryAction { get; set; }
    }
}
