//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speed
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Distance { get; set; }
        public int MonsterId { get; set; }
    
        public virtual Monster Monster { get; set; }
    }
}
