//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage
    {
        public int Id { get; set; }
        public string Damage_Type { get; set; }
        public string Damage_Dice { get; set; }
        public string ActionMonsterName { get; set; }
        public string ActionName { get; set; }
        public string LegendaryActionMonsterName { get; set; }
        public string LegendaryActionName { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual LegendaryAction LegendaryAction { get; set; }
    }
}
