//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorDnD5eInitiativeTracker.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class DifficultyClass
    {
        public int Id { get; set; }
        public string DC_Type { get; set; }
        public Nullable<short> DC_Value { get; set; }
        public Nullable<int> LegendaryActionId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string SpellName { get; set; }
    
        public virtual LegendaryAction LegendaryAction { get; set; }
        public virtual Action Action { get; set; }
        public virtual Spell Spell { get; set; }
    }
}
